-- =============================================================================
-- Migration: PIN Authentication (Phase 4.1)
-- Adds PIN-based auth support to profiles, a rate-limit lockout mechanism,
-- an audit_log table, and a safe public-facing staff directory view.
-- Run this in the Supabase SQL editor (or via `supabase db push`).
-- =============================================================================

-- 1. Extend profiles with PIN auth fields -------------------------------------
alter table public.profiles
  add column if not exists pin_hash text,
  add column if not exists is_active boolean not null default true,
  add column if not exists preferred_locale text not null default 'en'
    check (preferred_locale in ('en', 'ar')),
  add column if not exists location_id uuid null,
  add column if not exists failed_pin_attempts smallint not null default 0,
  add column if not exists locked_until timestamptz null;

-- role is assumed to already exist from Phase 0-3 scaffolding as
-- 'staff' | 'super_admin'. No change needed here.

-- 2. audit_log ------------------------------------------------------------
create table if not exists public.audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_actor_id_idx on public.audit_log (actor_id);
create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);

alter table public.audit_log enable row level security;

-- Only super_admins may read the audit log. All writes happen server-side
-- via the service role key (which bypasses RLS), so no insert policy
-- is granted to anon/authenticated roles.
drop policy if exists "audit_log_select_super_admin" on public.audit_log;
create policy "audit_log_select_super_admin"
  on public.audit_log for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'super_admin'
    )
  );

-- 3. Public staff directory (name only, no PIN hash) --------------------------
-- The login page needs to render "select who you are" without ever exposing
-- pin_hash, failed_pin_attempts, or lockout state to the client.
create or replace view public.staff_directory
  with (security_invoker = true) as
select id, full_name, role
from public.profiles
where is_active = true;

-- Allow anon (pre-login, on the /login page) to read only this view.
grant select on public.staff_directory to anon, authenticated;

-- Lock down direct profile reads for anon; authenticated users can only
-- read their own row. Adjust/merge with any existing profiles policies
-- from the Phase 0-3 schema.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

-- =============================================================================
-- Notes:
-- - pin_hash is written only by an admin-provisioning flow (Phase 4.x, not
--   part of this migration) using bcrypt, hashed server-side, never sent
--   to or generated by the client.
-- - Lockout policy: 5 failed attempts -> locked for 15 minutes (enforced in
--   application code in src/app/api/auth/login/route.ts, thresholds are
--   configurable via env vars).
-- =============================================================================
